### ISSUE TITLE
Wrong Klipper update command

### ISSUE THREAD

**Issue by mpx1986** [Esoterical/voron_canbus#23]
in mainboard flashen update klipper
python3 ~/katapult/scripts/flashtool.py -i can0 -u yourmainboarduuid -r

in toolheadflashing update klipper
python3 ~/katapult/scripts/flashtool.py -i can0 -u b6d9de35f24f -f ~/klipper/out/klipper.bin

without this /klipper/out/klipper.bin  you flash katapult an have a Devicename like this usb-katapult_stm32f446xx_37001A001851303439363932-if00

and no Geschwister Schneider Can Device.

**Comment by Esoterical** [comment]
This isn't an issue. You have missed steps. The `python3 ~/katapult/scripts/flashtool.py -i can0 -u yourmainboarduuid -r` Is there to put the mainboard into katapult bootloader mode (the -r means to reboot into bootloader), after that you can get a USB device and use the proper flash command.

It is further down the instructions. First you use the -r, then you use `python3 ~/katapult/scripts/flashtool.py -f ~/klipper/out/klipper.bin -d /dev/serial/by-id/usb-katapult_stm32f446xx_37001A001851303439363932-if00`
