### ISSUE TITLE
Suggestion to use 'sudo' in can_adapter/BigTreeTech U2C v2.1 instructions

### ISSUE THREAD

**Issue by floergri** [Esoterical/voron_canbus#27]
Described steps will fail if user permissions are not sufficient
using `sudo `with all the commands will fix this

**Comment by mutlubasdas** [comment]
I agree to this.
Without adding sudo I was getting access error.

**Comment by Esoterical** [comment]
I believe the need to "sudo" the dfu-util commands is a fairly recent bookworm/new distro thing. Anyway, I've added the sudo to the instructions for the u2c flashing page.
